server.host=http://194.195.87.149/

management.endpoints.web.cors.allowed-origins=https://dashboard.dataox.io
management.endpoints.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
management.endpoints.web.cors.allowed-headers=*
management.endpoints.web.cors.allow-credentials=true
management.endpoints.web.cors.max-age=3600
