#app configs
spring.application.name=clickup-google-calendar-agenda
server.port=4846
server.servlet.context-path=/api
spring.profiles.active=prod

#db configs
spring.data.mongodb.uri=mongodb://root:secret@localhost:27017/mydatabase?authSource=admin

#google credentials configs
google.calendar_id=oleksandr.melnyk@data-ox.com

#google oauth configs
google.oauth.client_id=1088161903353-btlpmnava83leeg3colnod4s6s5npf2l.apps.googleusercontent.com
google.oauth.client_secret=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
google.oauth.redirect_uri=https://dashboard.dataox.io

#clickup configs
clickup.api_key=pk_93644911_EERJSVSS3N7ZVQQUFTWH4KUOT0NYQOYE
