#app props
spring.application.name=clickup-google-calendar-agenda
spring.profiles.active=prod

server.port=4846
server.servlet.context-path=/api

#jwt props
security.jwt.secret-key=4c7df0526adeffd7d8bf719d37076708d078b66dfba3fbc0b39bd637a4846d61
security.jwt.access-expiration-time=14400000
security.jwt.refresh-expiration-time=28800000

#client props
web.client.prod-url=https://dashboard.dataox.io
web.client.dev-url=http://localhost:3520
web.client.redirect-url=https://dashboard.dataox.io/check-oauth

web.backend.domain=integration.dataox.io
web.backend.click-up-webhook-path=/api/click-up/webhook

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=melnukoleksandr2023@gmail.com
spring.mail.password=bdygrhmgwlvlbkwr
spring.mail.to=oleksandr.melnyk@data-ox.com,liudmyla.ivanytska@data-ox.com
spring.mail.from=no-reply@gmail.com
spring.mail.reply-to=no-reply
spring.mail.properties.protocol=smtp
spring.mail.properties.auth=true
spring.mail.properties.starttls.enabled=true

#google oauth props
google.oauth.client-id=1046165274420-d7v9919vmo5cek72av7a7ece3450qts8.apps.googleusercontent.com
google.oauth.client-secret=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

#clickup props
click-up.oauth.client-id=QKB7N09WVO5GSJ2NIBFBW8Q0K5PUWPAU
click-up.oauth.client-secret=38A7VZGTTF7Z19SSLAS5DVYF2S9XUTNK2YVQ7RILYH8ILWXPOMGUVYJYQ4OT4MPV
